### ISSUE TITLE
unexpected results

### ISSUE THREAD

**Issue by sbytov** [gpichot/cpp-tdigest#4]
Hi,
I was looking for an implementation of t-digest and I followed the link from its github project site to your cpp implementation.
Unfortunately this test code doesn't give me any sensible results.
Can you please comment on this? Is my using of your implementation is incorrect?

	TDigest* tdigest = new TDigest(10);	
        const int nrolls = 10000;  // number of experiments
	std::default_random_engine generator;
	std::normal_distribution<double> distribution(50.0, 20.0);
        for (int i = 0; i < nrolls; ++i) 
	{
		double number = distribution(generator);
		tdigest->add((int)number);
	}
        cout << "MEDIAN: " << tdigest->quantile(0.5) << endl;
	cout << "99-PERCENTILE: " << tdigest->quantile(0.99) << endl;

Here is the output I get:
      MEDIAN: -6.27744e+66
      99-PERCENTILE: -6.27744e+66

**Comment by gpichot** [comment]
Hi @sbytov,

I did this a long time ago but it's not maintained anymore. I advise you to look at the following implementation : https://github.com/derrickburns/tdigest

See related discussion: https://github.com/tdunning/t-digest/issues/88

**Comment by sbytov** [comment]
Thanks for pointing me out in the right direction, Gabriel!

**Comment by gpichot** [comment]
You're welcome
